// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Unified sidebar for main docs instance (routeBasePath: "/")
  docSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "Services",
      items: [
        {
          type: "link",
          label: "Services Overview",
          href: "/service",
        },
      ],
    },
  ],
  // Unified sidebar for services instance (routeBasePath: "/service")
  // Docusaurus uses the instance ID "services" as the sidebar name
  services: [
    {
      type: "link",
      label: "Home",
      href: "/",
    },
    {
      type: "doc",
      id: "index",
      label: "Services",
    },
  ],
};

module.exports = sidebars;
